name: meu primeiro projeto cicd

on:
    push:
        branches:
            -master

jobs:
    print-test:
        runs-on: ubuntu-latest
        steps:
            - run: echo "AGORA FOI! O Actions encontrou o arquivo!"