name: CI/CD - Criar Banco de Dados no RDS AWS

on:
  push:
    branches:
      - master

jobs:
  criar-banco-de-dados:
    runs-on: ubuntu-latest

    steps:
      # 1. Baixa o código do repositório
      - name: Checkout do código
        uses: actions/checkout@v4

      # 2. Instala a ferramenta sqlcmd no runner do GitHub
      - name: Instalar SQL Server Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y mssql-tools18 unixodbc-dev
          echo "/opt/mssql-tools18/bin" >> $GITHUB_PATH

      # 3. Conecta no RDS (banco master) e cria o banco EMPRESA
      - name: Executar criação do banco EMPRESA
        env:
          DB_ENDPOINT: ${{ secrets.DB_ENDPOINT }}
          DB_USER: ${{ secrets.DEVELOPER_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: |
          sqlcmd -S "$DB_ENDPOINT" -U "$DB_USER" -P "$DB_PASSWORD" -d "master" -i Script/init.sql -C